---
name: Build Docker Image

on: push

jobs:
  build:
    runs-on : ubuntu-latest
    name: Build Docker Apps
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Image
        run: |
          cd node
          docker build -t temp/build
      - name: Push Docker
        run: |
          docker tag temp/build zahrikargo/assignment:latest
          docker tag temp/build zahrikargo/assignment:${{ github.sha }} 
          docker push zahrikargo/assignment:latest
          docker push zahrikargo/assignment:${{ github.sha }}