---
name: Build Docker Image

on: push

jobs:
  build:
    runs-on : ubuntu-latest
    name: Build Docker Apps
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        run: docker build -t temp/build
      
