---
name: Run Unit Tests

on:
 push:
<<<<<<< HEAD
   branches:
     - master
=======
   branches: master
>>>>>>> master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node Js
        run: sudo apt update && sudo apt install nodejs
      
